version: "3"
volumes:
  postgres-store:
  users-volume:
services:
  postgres:
    image: postgres
    container_name: postgres-book-store
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "BookStore@123"
    volumes:
      - "postgres-store:/var/lib/postgresql/data"
  consul:
    image: consul
    container_name: consul-book-store
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - 8500:8500
  users-migrations:
    build: ./users/src/Users.Migrations
    container_name: users-migrations-book-store
    environment:
      ConnectionString: "Server=postgres;Database=bookstoreuser;User Id=postgres;Password=BookStore@123;"
    volumes:
      - "users-volume:/var/output"
    entrypoint: /bin/sh -c "rm -f /var/output/migrator.txt && dockerize -wait tcp://postgres:5432 sh /docker-entrypoint.sh"
    depends_on:
      - postgres
  users:
    build: ./users
    container_name: users-book-store
    entrypoint: dockerize -wait file:///var/output/migrator.txt dotnet /app/Users.Web.dll
    environment:
       ASPNETCORE_ENVIRONMENT: "Development"
       ConnectionStrings__Postgres: "Server=postgres;Database=bookstoreuser;User Id=postgres;Password=BookStore@123;"
       #ASPNETCORE_Kestrel__Certificates__Default__Password: "BookStoreUsers@123"
       #ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/users-book-store.pfx"
    volumes:
      - "users-volume:/var/output"
      #- "~/.aspnet/https:/https"
    ports:
      - '5100:5100'
      - '5101:5101'
    depends_on:
      - postgres
      - users-migrations
      - consul
  # ravendb: 
  #   image: ravendb/ravendb
  #   container_name: raven-book-store
  #   ports:
  #     - 8080:8080