version: "3"
volumes:
  postgres-store:
services:
  postgres:
    image: postgres
    container_name: postgres-book-store
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "BookStore@123"
    volumes:
      - "postgres-store:/var/lib/postgresql/data"
  users-migrations:
    build: ./users/src/Users.Migrations
    container_name: users--migrations-book-store
    depends_on:
      - postgres
  users:
    build: ./users
    container_name: users-book-store
    ports:
      - 5100:5100
    depends_on:
      - postgres
      - users-migrations
  # ravendb: 
  #   image: ravendb/ravendb
  #   container_name: raven-book-store
  #   ports:
  #     - 8080:8080